estimators:
  - name: KNeighborsClassifier
    source_path: sklearn.neighbors.KNeighborsClassifier
    hyperparameters:
      n_neighbors:
        - 1
        - 5
        - 10
        - 50
        - 1e2
      algorithm:
        - brute
      n_jobs:
        - -1
        - 1
    accepts_labels: True
    metrics:
      - accuracy_score
      - roc_auc
    datasets:
      - generator: classification
        n_features: 1e2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 10
          - 1e2
          - 1e3
          - 1e4

  - name: daal4py_KNeighborsClassifier
    source_path: daal4py.sklearn.neighbors.KNeighborsClassifier
    inherit: KNeighborsClassifier
