estimators:
  KNeighborsClassifier:
    name: KNeighborsClassifier
    source_path: sklearn.neighbors.KNeighborsClassifier
    hyperparameters:
      n_neighbors:
        - 1
        - 5
        - 10
        - 50
        - 100
      algorithm:
        - brute
      n_jobs:
        - -1
        - 1
    accepts_labels: True
    metrics:
      - accuracy_score
      - roc_auc_score
    datasets:
      - generator: classification
        n_features: 100
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 10
          - 100
          # - 1000
          # - 10000
  daal4py_KNeighborsClassifier:
    name: daal4py_KNeighborsClassifier
    source_path: daal4py.sklearn.neighbors.KNeighborsClassifier
    inherit: KNeighborsClassifier
