algorithms:
  - name: KNeighborsClassifier
    class: sklearn.neighbors.KNeighborsClassifier
    hyperparameters:
      n_neighbors:
        - 1
        - 5
        - 10
        - 50
        - 1e2
      algorithm: brute
      n_jobs:
        - -1
        - 1
    accepts_labels: True
    metrics:
      - accuracy
      - roc_auc
    datasets:
      - generator: sklearn.datasets.make_classification
        n_features: 1e2
        train:
          n_samples: 1e6
        test:
          n_samples:
            - 1
            - 10
            - 1e2
            - 1e3
            - 1e4

  - name: daal4py_KNeighborsClassifier
    class: daal4py.sklearn.neighbors.KNeighborsClassifier
    inherit: KNeighborsClassifier
