estimators:
  KNeighborsClassifier:
    name: KNeighborsClassifier
    source_path: sklearn.neighbors.KNeighborsClassifier
    hyperparameters:
      n_neighbors:
        - 1
        - 5
        - 10
        - 50
        - 1e2
      algorithm:
        - brute
      n_jobs:
        - -1
        - 1
    metrics:
      - accuracy_score
      - roc_auc_score
    datasets:
      - generator: classification
        n_features: 1e2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 1e3
      - generator: classification
        n_features: 2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 1e3
  daal4py_KNeighborsClassifier:
    inherit: KNeighborsClassifier
    source_path: daal4py.sklearn.neighbors.KNeighborsClassifier
  KMeans:
    name: KMeans
    source_path: sklearn.cluster.KMeans
    hyperparameters:
      init:
        - k-means++
        - random
      n_clusters:
        - 8
      max_iter:
        - 30
      n_init:
        - 1
      tol:
        - 1e-16
    metrics:
      - adjusted_rand_score
    datasets:
      - generator: blobs
        n_features: 2
        n_samples_train:
          - 1e4
        n_samples_test:
          - 1
          - 1e3
      - generator: blobs
        n_features: 1e2
        n_samples_train:
          - 1e4
        n_samples_test:
          - 1
          - 1e3
      - generator: blobs
        n_features: 2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 1e3
      - generator: blobs
        n_features: 1e2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 1e3
  daal4py_KMeans:
    inherit: KMeans
    source_path: daal4py.sklearn.cluster.KMeans
