estimators:
  KNeighborsClassifier:
    name: KNeighborsClassifier
    estimator: sklearn.neighbors.KNeighborsClassifier
    hyperparameters:
      n_neighbors:
        - 1
        - 5
      algorithm:
        - brute
      n_jobs:
        - -1
        - 1
    metrics:
      - accuracy_score
    datasets:
      - sample_generator: sklearn.datasets.make_classification
        params:
          n_classes: 2
          n_redundant: 0
          random_state: 42
        n_features: 2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1

  KNeighborsClassifier_kd_tree:
    name: KNeighborsClassifier_kd_tree
    estimator: sklearn.neighbors.KNeighborsClassifier
    hyperparameters:
      n_neighbors:
        - 1
        - 5
      algorithm:
        - kd_tree
      n_jobs:
        - -1
        - 1
    metrics:
      - accuracy_score
    datasets:
      - sample_generator: sklearn.datasets.make_classification
        params:
          n_classes: 2
          n_redundant: 0
          random_state: 42
        n_features: 2
        n_samples_train:
          - 1e6
        n_samples_test:
          - 1
          - 1e3

  daal4py_KNeighborsClassifier_kd_tree:
    inherit: KNeighborsClassifier_kd_tree
    estimator: daal4py.sklearn.neighbors.KNeighborsClassifier

  daal4py_KNeighborsClassifier:
    inherit: KNeighborsClassifier
    estimator: daal4py.sklearn.neighbors.KNeighborsClassifier
  KMeans:
    name: KMeans
    estimator: sklearn.cluster.KMeans
    hyperparameters:
      init:
        - k-means++
        - random
      n_clusters:
        - 3
        - 8
        - 10
      max_iter:
        - 30
      n_init:
        - 1
      tol:
        - 1e-16
    metrics:
      - adjusted_rand_score
    datasets:
      - sample_generator: sklearn.datasets.make_blobs
        params:
          random_state: 42
        n_features: 2
        n_samples_train:
          - 1e4
        n_samples_test:
          - 1
          - 1e3
      - sample_generator: sklearn.datasets.make_blobs
        params:
          random_state: 42
        n_features: 1e2
        n_samples_train:
          - 1e4
        n_samples_test:
          - 1
          - 1e3

  daal4py_KMeans:
    inherit: KMeans
    estimator: daal4py.sklearn.cluster.KMeans
