name: sklearn benchmark suite

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml pandas scikit-learn numpy \
            matplotlib seaborn scikit-learn-intelex \
            plotly==4.14.3 nbconvert

      - name: run benchmark suite
        run: python -m sklearn_benchmarks

      - name: convert notebook to html
        run: jupyter nbconvert --to html --execute sklearn_benchmarks/results/viz.ipynb

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: sklearn_benchmarks/results
