name: scikit-learn benchmark suite

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p
          rm ~/miniconda.sh
          conda config --add channels conda-forge
          conda config --add channels intel
          conda env create -f environment.yml
          conda init bash
          sudo reboot
          conda activate sklbench

      # - name: install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install pyyaml pandas scikit-learn numpy \
      #       matplotlib scikit-learn-intelex \
      #       plotly==4.14.3 nbconvert

      - name: Run benchmark suite
        run: python -m sklearn_benchmarks

      - name: Convert notebook to html
        run: jupyter nbconvert --to html --execute sklearn_benchmarks/results/viz.ipynb

      - name: Upload benchmark results artifact
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: sklearn_benchmarks/results
