name: scikit-learn benchmark suite

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: config.yml
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('bench_environment.yml') }}

      - name: Setup miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.8
          activate-environment: sklbench
          environment-file: bench_environment.yml
          channels: conda-forge,intel
          channel-priority: flexible
          use-only-tar-bz2: true

      - name: Run benchmark suite
        run: python -m sklearn_benchmarks

      - name: Convert notebook to html
        run: |
          jupyter nbconvert --to html --execute sklearn_benchmarks/results.ipynb
          rm -rf docs
          mkdir docs
          mv sklearn_benchmarks/results.html docs/index.html

      - name: Upload docs folder
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs

      - name: Upload benchmark results
        uses: actions/upload-artifact@v2
        with:
          name: benchmark-results
          path: sklearn_benchmarks/results

      - name: Download docs folder
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: docs
