name: Sklearn Benchmark Suite

on:
  push:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pyyaml
          pip3 install pandas
          pip3 install sklearn
          pip3 install numpy
          pip3 install matplotlib
          pip3 install seaborn
          wget https://registrationcenter-download.intel.com/akdlm/irc_nas/17766/l_AIKit_p_2021.2.0.1101.sh
          sudo bash l_AIKit_p_2021.2.0.1101.sh
          pip3 install scikit-learn-intelex

      - name: Execute benchmark script
        run: python3 -m sklearn_benchmarks
